import { Router } from 'express';
import { requireAdmin } from '../middleware/authMiddleware.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { getDashboard } from '../controllers/dashboardController.js';
import projectRoutes from './projectRoutes.js';
import resumeRoutes from './resumeRoutes.js';
import settingsRoutes from './settingsRoutes.js';
import messageRoutes from './messageRoutes.js';
import certificateRoutes from './certificateRoutes.js';
import mediaRoutes from './mediaRoutes.js';
import accountRoutes from './accountRoutes.js';
import educationRoutes from './educationRoutes.js';
import profileRoutes from './profileRoutes.js';
import { createResourceRoutes } from './resourceRoutes.js';
import Skill from '../models/Skill.js';
import SkillCategory from '../models/SkillCategory.js';
import TimelineItem from '../models/TimelineItem.js';
import Service from '../models/Service.js';

const router = Router();
router.use(requireAdmin);
router.get('/dashboard', asyncHandler(getDashboard));
router.use('/projects', projectRoutes);
router.use('/skills', createResourceRoutes(Skill, 'skill', { populate: 'category' }));
router.use('/skill-categories', createResourceRoutes(SkillCategory, 'category'));
router.use('/timeline', createResourceRoutes(TimelineItem, 'timeline'));
router.use('/experience', createResourceRoutes(TimelineItem, 'timeline'));
router.use('/education', educationRoutes);
router.use('/profile', profileRoutes);
router.use('/services', createResourceRoutes(Service, 'service'));
router.use('/resume', resumeRoutes);
router.use('/resumes', resumeRoutes);
router.use('/certificates', certificateRoutes);
router.use('/media', mediaRoutes);
router.use('/account', accountRoutes);
router.use('/settings', settingsRoutes);
router.use('/messages', messageRoutes);
export default router;
